import static org.junit.Assert.assertTrue;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class LibraryTest {
    @Test (groups="abc")
    public void testSomeLibraryMethod() {
    	 System.setProperty("webdriver.chrome.driver","C:\\Users\\Deepak\\eclipse-workspace\\Sdet_Project\\chromedriver.exe");  
    	WebDriver driver=new ChromeDriver();
    	driver.get("https://www.google.com/");
    }
    @Test (groups="fb")
    public void te1() {
    	 System.setProperty("webdriver.chrome.driver","C:\\Users\\Deepak\\eclipse-workspace\\Sdet_Project\\chromedriver.exe");  
    	WebDriver driver=new ChromeDriver();	
    	driver.get("https://www.facebook.com/");
    }
}